language: node_js
node_js:
  - 12
services:
  - docker
script:
  # Build
  - docker-compose -f docker-compose-build.yaml build
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push
  - docker-compose -f docker-compose-build.yaml push