language: node_js
node_js:
  - 12
services:
  - docker
script:
  # Build
  - docker-compose -f docker-compose-build.yaml build
  # Tagging
  - docker tag udagram-api-feed phuoc05pp/udagram-api-feed:latest
  - docker tag udagram-api-user phuoc05pp/udagram-api-user:latest
  - docker tag udagram-frontend phuoc05pp/udagram-frontend:latest
  - docker tag reverseproxy phuoc05pp/reverseproxy:latest
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push
  - docker-compose -f docker-compose-build.yaml push