language: node_js
node_js:
  - 12
services:
  - docker
script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed phuoc05pp/udagram-api-feed:latest
  - docker tag udagram-api-user phuoc05pp/udagram-api-user:latest
  - docker tag udagram-frontend phuoc05pp/udagram-frontend:latest
  - docker tag reverseproxy phuoc05pp/reverseproxy:latest
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push
  - docker push phuoc05pp/udagram-api-feed:latest
  - docker push phuoc05pp/udagram-api-user:latest
  - docker push phuoc05pp/udagram-frontend:latest
  - docker push phuoc05pp/reverseproxy:latest